name: Deploy to GitHub Pages

on:
  # Déclenchement à chaque push sur la branche main
  push:
    branches: [ main ]
  
  # Permettre le déclenchement manuel du workflow
  workflow_dispatch:

# Définir les permissions nécessaires pour le déploiement sur GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Éviter les déploiements simultanés
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job pour construire et déployer
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Configurer GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      
      # Pas besoin d'étape de build, projet HTML/CSS/JS simple
      
      # Créer l'artefact de déploiement
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Utiliser le dossier racine
      
      # Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      # Afficher l'URL du site déployé
      - name: Display deployed URL
        run: echo "🚀 Your site is deployed at ${{ steps.deployment.outputs.page_url }}"